apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: $__env{INFLUXDB_ORG}
      defaultBucket: $__env{INFLUXDB_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      token: $__env{INFLUXDB_TOKEN}
    isDefault: true
    editable: false

  - name: InfluxDB Downsampled
    uid: influxdb-downsampled
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: $__env{INFLUXDB_ORG}
      defaultBucket: gpu_metrics_downsampled
      tlsSkipVerify: true
    secureJsonData:
      token: $__env{INFLUXDB_TOKEN}
    isDefault: false
    editable: false

  - name: InfluxDB Hourly
    uid: influxdb-hourly
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: $__env{INFLUXDB_ORG}
      defaultBucket: gpu_metrics_hourly
      tlsSkipVerify: true
    secureJsonData:
      token: $__env{INFLUXDB_TOKEN}
    isDefault: false
    editable: false
